### PR TITLE
Skip git run on target and fill revision correctly

### PR DESCRIPTION
**Pull request by agavrik**
Issue description: capistrano 3 tries to run git on target for git:check and git:create_release (which fails since there may be no access to local repo from target system). Also revision version is not passed to target system.
Root cause: Without Rake::Task.clear new task definition is not replacing, but appending new functionality.
Solution: Added clear of git:check, git:create_release and git:set_revision. Fill current_revision capistrano variable after cloning locally

### CODE REVIEW

**Comment by ivalentinee** [comment]
+1

**Comment by havramar** [comment]
+1

**Comment by agavrik** [comment]
In fact, I think that was the wrong way of doing it (at least if you only need git). You just need to set :scm to :rsync in deploy.rb. And take some other fixes in pull-requests around. So I based on https://github.com/STRML/capistrano-rsync and added support for passing server port to rsync and updated README into https://github.com/agavrik/capistrano-rsync. It is pull-requested to STRML as well.

**Comment by agavrik** [comment]
So I just closed this pull request as now this PR has my changes as well - https://github.com/moll/capistrano-rsync/pull/13

**Pull request closed without merging**
